services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    container-name: nginx
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    container-name: mariadb