--Initialize database
CREATE DATABASE IF NOT EXITS $DB_NAME CHARACTER SET utf8 COLLATE utf8_general_ci;
USE $DB_NAME;
CREATE USER IF NOT EXISTS $DB_USER@'%' IDENTIFIED BY $DB_PASS;
GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USER@'%';
FLUSH PRIVILEGES;